### ISSUE TITLE
Cannot override hocon configuration with env variables

### ISSUE THREAD

**Issue by psilos** [sksamuel/hoplite#115]
Hello, 

It seems that when I try to override my HOCON configuration with env variables like this: 

```
mongo {
  hostname = "localhost"
  hostname = ${?MONGO_HOSTNAME}
}
```

and load configuration with: 

`val config = ConfigLoader().loadConfigOrThrow<Conf>("/application.conf")`

hoplite throws the following error: 

`com.typesafe.config.ConfigException$NotResolved: called valueType() on value with unresolved substitutions, need to Config#resolve() first, see API docs
	at com.typesafe.config.impl.ConfigDelayedMerge.valueType(ConfigDelayedMerge.java:46)
	at com.sksamuel.hoplite.hocon.ValueProduction.invoke(HoconParser.kt:51)
	at com.sksamuel.hoplite.hocon.MapProduction.invoke(HoconParser.kt:41)
	at com.sksamuel.hoplite.hocon.ValueProduction.invoke(HoconParser.kt:52)
	at com.sksamuel.hoplite.hocon.MapProduction.invoke(HoconParser.kt:41)
	at com.sksamuel.hoplite.hocon.HoconParser.load(HoconParser.kt:27)
	at com.sksamuel.hoplite.ConfigFilePropertySource$node$1.invoke(PropertySource.kt:92)
	at com.sksamuel.hoplite.ConfigFilePropertySource$node$1.invoke(PropertySource.kt:86)
	at com.sksamuel.hoplite.arrow.ValidationsKt.ap(validations.kt:23)
	at com.sksamuel.hoplite.ConfigFilePropertySource.node(PropertySource.kt:91)
	at com.sksamuel.hoplite.ConfigLoader.loadNode(ConfigLoader.kt:161)
	at com.sksamuel.hoplite.ConfigLoader.loadConfig(ConfigLoader.kt:149)`

This is the default HOCON way of overriding with env variables, is there an alternative syntax to use?

**Comment by sksamuel** [comment]
I guess hoplite should call .resolve on sources coming from hocon to fix that.

**Comment by sksamuel** [comment]
The other way you can do it is using hoplite's format for ENV vars. ${VAR}

**Comment by psilos** [comment]
Thanks for the quick response @sksamuel , I believe the first option is preferable to be fully compatible with HOCON, as this syntax means it would override the value only if it's present, does the later convey the same semantics ?

**Comment by sksamuel** [comment]
No you're right, I'll do it the first way.

**Comment by psilos** [comment]
Hi @sksamuel , do you think that this is an easy fix of calling .resolve() to override default values with env variables? Or are you concerned that this may conflict with `hoplite`s way of overriding values ?

**Comment by sksamuel** [comment]
I think calling .resolve() inside the Hocon parser should be sufficient.

**Comment by sksamuel** [comment]
This is fixed in 1.2.1.

**Comment by psilos** [comment]
thanks for the quick fix @sksamuel , looking forward to `1.2.1` release

**Comment by psilos** [comment]
hi @sksamuel sorry to bug you again, was wondering if there is a schedule for this release :) 

Really keen to put in good use :P

**Comment by sksamuel** [comment]
I don't know why it's not showing up. I've released it in sonatype. I'll
try again tonight.

**Comment by sksamuel** [comment]
1.2.2 is out btw.

**Comment by psilos** [comment]
Many thanks for this! I will be using it straight away!
