### ISSUE TITLE
No decoders registered

### ISSUE THREAD

**Issue by haste2** [sksamuel/hoplite#221]
Trying to use the json parser in conjunction with custom task to test a google cloud function locally. Not sure why default decoders can't be registered. Pretty sure running through the invoker below is causing this. 

task<JavaExec>("runFunction") {
    main = "com.google.cloud.functions.invoker.runner.Invoker"
    classpath(invoker)
    inputs.files(configurations.runtimeClasspath, sourceSets["main"].output)
    args(
        "--target", project.findProperty("runFunction.target") ?: "dev.mwhyte.function.App",
        "--port", project.findProperty("runFunction.port") ?: 8080
    )
    doFirst {
        args("--classpath", files(configurations.runtimeClasspath, sourceSets["main"].output).asPath)
    }
}

tasks.named("build") {
    dependsOn(":shadowJar")
}

from config class:

private val jsonParser = JsonParser()
    fun loadConfig(): Config = ConfigLoader.Builder()
        .addFileExtensionMapping("json", jsonParser)
        .addSource(PropertySource.resource("/config.json"))
        .build()
        .loadConfig<Config>()
        .getOrElse { throw Exception(it.description()) }

**Comment by sksamuel** [comment]
What's the error you get ?

**Comment by haste2** [comment]
2021-08-17 23:20:22.820:INFO::main: Logging initialized @264ms to org.eclipse.jetty.util.log.StdErrLog
Exception in thread "main" java.lang.RuntimeException: Could not construct an instance of dev.mwhyte.function.App: java.lang.reflect.InvocationTargetException
	at com.google.cloud.functions.invoker.NewHttpFunctionExecutor.forClass(NewHttpFunctionExecutor.java:55)
	at com.google.cloud.functions.invoker.runner.Invoker.servletForDeducedSignatureType(Invoker.java:358)
	at com.google.cloud.functions.invoker.runner.Invoker.startServer(Invoker.java:290)
	at com.google.cloud.functions.invoker.runner.Invoker.main(Invoker.java:140)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.google.cloud.functions.invoker.NewHttpFunctionExecutor.forClass(NewHttpFunctionExecutor.java:51)
	... 3 more
Caused by: java.lang.Exception: No decoders are registered
Caused by: java.lang.reflect.InvocationTargetException

	at AuthConfigLoader$loadConfig$1.invoke(AuthConfigLoader.kt:13)
	at AuthConfigLoader$loadConfig$1.invoke(AuthConfigLoader.kt:13)
	at com.sksamuel.hoplite.fp.ValidatedKt.getOrElse(Validated.kt:93)
	at AuthConfigLoader.loadConfig(AuthConfigLoader.kt:13)
	at dev.mwhyte.function.App$client$1.invoke(App.kt:49)
	at dev.mwhyte.function.App$client$1.invoke(App.kt:46)
	at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:41)
	at dev.mwhyte.function.App.<init>(App.kt:46)
	... 8 more

Caused by: java.lang.Exception: No decoders are registered

Execution failed for task ':runFunction'.
> Process 'command '/Users/hari/Library/Java/JavaVirtualMachines/corretto-11.0.12/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by haste2** [comment]
Hey @sksamuel can I provide any more information that would help? I am still stuck trying to figure this out.

**Comment by haste2** [comment]
Modified my class path (experimenting) and now i am getting the following error. 

2021-08-23T11:00:46.879+0200 [ERROR] [system.err] Caused by: java.util.ServiceConfigurationError: com.sksamuel.hoplite.decoder.Decoder: com.sksamuel.hoplite.decoder.UUIDDecoder not a subtype
Caused by: java.util.ServiceConfigurationError: com.sksamuel.hoplite.decoder.Decoder: com.sksamuel.hoplite.decoder.UUIDDecoder not a subtype

2021-08-23T11:00:46.879+0200 [ERROR] [system.err] 	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
2021-08-23T11:00:46.879+0200 [ERROR] [system.err] 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1237)
2021-08-23T11:00:46.879+0200 [ERROR] [system.err] 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
2021-08-23T11:00:46.879+0200 [ERROR] [system.err] 	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
2021-08-23T11:00:46.880+0200 [ERROR] [system.err] 	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
2021-08-23T11:00:46.880+0200 [ERROR] [system.err] 	at kotlin.collections.CollectionsKt___CollectionsKt.toCollection(_Collections.kt:1293)
2021-08-23T11:00:46.880+0200 [ERROR] [system.err] 	at kotlin.collections.CollectionsKt___CollectionsKt.toMutableList(_Collections.kt:1326)
2021-08-23T11:00:46.880+0200 [ERROR] [system.err] 	at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1317)
2021-08-23T11:00:46.880+0200 [ERROR] [system.err] 	at com.sksamuel.hoplite.decoder.DecoderRegistryKt.defaultDecoderRegistry(DecoderRegistry.kt:63)
2021-08-23T11:00:46.880+0200 [ERROR] [system.err] 	at com.sksamuel.hoplite.ConfigLoader$Builder.build(ConfigLoader.kt:193)
2021-08-23T11:00:46.881+0200 [ERROR] [system.err] 	at com.ingka.ose.findPrinters.AuthConfigLoader.loadConfig(AuthConfigLoader.kt:13)

**Comment by haste2** [comment]
Fixed by using a different classloader (withClassLoader)
