### ISSUE TITLE
Allow manual registration of decoders

### ISSUE THREAD

**Issue by 2x2xplz** [sksamuel/hoplite#254]
Like #221, I tried to move an API I'd built using Hoplite to Google Cloud Functions, but it failed with "No decoders are registered" error. I built a very basic project to strip out any other possible issues but continue to get this error. (The only other dependency is http4k, which creates the mandatory `HttpFunction`) This application works fine on my local machine (I pass the config via a -D argument with a JSON string as the value). The application also worked on GCF without Hoplite (i.e. no config, everything hard-coded).

The stacktrace is:

```
Exception in thread "main" java.lang.RuntimeException: Could not construct an instance of GCFEntryPoint: java.lang.reflect.InvocationTargetException at com.google.cloud.functions.invoker.HttpFunctionExecutor.forClass(HttpFunctionExecutor.java:57) at com.google.cloud.functions.invoker.runner.Invoker.startServer(Invoker.java:243) at com.google.cloud.functions.invoker.runner.Invoker.main(Invoker.java:121) Caused by: java.lang.reflect.InvocationTargetException at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) at com.google.cloud.functions.invoker.HttpFunctionExecutor.forClass(HttpFunctionExecutor.java:53) ... 2 more Caused by: java.lang.ExceptionInInitializerError at Greeter.invoke(Main.kt:39) at Greeter.invoke(Main.kt:38) at org.http4k.serverless.GoogleCloudHttpFunction._init_$lambda-0(GoogleCloudHttpFunction.kt:19) at org.http4k.serverless.GoogleCloudHttpFunction.<init>(GoogleCloudHttpFunction.kt:23) at org.http4k.serverless.GoogleCloudHttpFunction.<init>(GoogleCloudHttpFunction.kt:19) at GCFEntryPoint.<init>(Main.kt:42) ... 7 more Caused by: com.sksamuel.hoplite.ConfigException: Error loading config because:
No decoders are registered
at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:393)
at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:390)
at com.sksamuel.hoplite.fp.ValidatedKt.getOrElse(Validated.kt:93)
at com.sksamuel.hoplite.ConfigLoader.returnOrThrow(ConfigLoader.kt:390)
at MainKt.<clinit>(Main.kt:43)
... 13 more
```

Just an experiment, I got the same error whether or not I had defined a Runtime Variable for the function. In other words, even when there is no configuration for Hoplite to import, the same error occurs.

I attached a ZIP file with the very basic project (1 file + gradle) if you'd like to take a look: [HopliteGCFTest.zip](https://github.com/sksamuel/hoplite/files/7828551/HopliteGCFTest.zip)

#221 seemed to have found a way to get his project working (a custom classLoader?) but there's no detail or clues on how to replicate what he did.

Thanks. I have successfully deployed to AWS Lambda using Hoplite and would like the option of GCF (and Azure, which I haven't tested yet) as well.

**Comment by sksamuel** [comment]
I guess its something to do with the classloader not finding the decoders via service files.
We should add an option to manually register them.

**Comment by sksamuel** [comment]
Completed in master.
