### ISSUE TITLE
Merging with yaml anchors is broken based on dotpath check

### ISSUE THREAD

**Issue by azban** [sksamuel/hoplite#307]
it looks like the recent work on adding dotpath has broken merging for yaml with anchors/aliases. it's a little hard for me to understand a good fix, but i created a branch with an example of a failing test. happy to take a stab at a fix if someone could point me in the right direction.

https://github.com/sksamuel/hoplite/compare/master...azban:yaml-alias-merging

```
Trying to merge node with path DotPath(keys=[righthand]) with node with path DotPath(keys=[lefthand])
java.lang.IllegalArgumentException: Trying to merge node with path DotPath(keys=[righthand]) with node with path DotPath(keys=[lefthand])
	at com.sksamuel.hoplite.FallbackKt.merge(fallback.kt:12)
	at com.sksamuel.hoplite.FallbackKt.merge(fallback.kt:21)
	at com.sksamuel.hoplite.NodeParser.parseNode(NodeParser.kt:36)
	at com.sksamuel.hoplite.ConfigLoader.loadConfig(ConfigLoader.kt:136)
```

**Comment by sksamuel** [comment]
The anchor is resolved inside the same file, not across files. I'm not sure your example would ever have worked ?
This would require hoplite to track anchors across all files as they are loaded, which maybe we can do.

**Comment by azban** [comment]
i'm not expecting the anchors to be resolved across files. `anchor-merge-base.yml` doesn't have references to the anchors in `anchor.yml`.

i would expect that the anchors in `anchor.yml` resolve independently before trying to merge the files, which is what is currently failing.
