### ISSUE TITLE
Env and snakecase variable throwing unused error with strict()

### ISSUE THREAD

**Issue by bt-wil** [sksamuel/hoplite#312]
I'm seeing an unexpected behavior with strict mode and variable naming in the config file.  I'm using snake case for configuration, and the issue arises when there is an environment variables that overwrite specific config.

good.yaml
```
connectTimeout: 10
```

bad.yaml
```
connect_timeout: 100
```

code using v2.1.5
```
import com.sksamuel.hoplite.ConfigLoaderBuilder
import com.sksamuel.hoplite.addFileSource
import com.sksamuel.hoplite.sources.EnvironmentVariablesPropertySource
import java.io.File

data class Config(val connectTimeout: Int)

fun makeConfig(configFile: String, envVars: Map<String, String>): Config {
    val envSource =
        EnvironmentVariablesPropertySource(
            useUnderscoresAsSeparator = true,
            allowUppercaseNames = true,
        ) { envVars }
    return ConfigLoaderBuilder.default()
        .addPropertySource(envSource)
        .addFileSource(File(configFile))
        .strict()
        .build()
        .loadConfigOrThrow()
}

fun main() {
    val prefix = "SERVICE_"
    val envVars =
        System.getenv().filterKeys { it.startsWith(prefix) }.mapKeys { it.key.removePrefix(prefix) }

    println("Env vars: $envVars")

    val goodConfig = makeConfig("good.yaml", envVars)
    println("good  $goodConfig")

    val badConfig = makeConfig("bad.yaml", envVars)
    println("bad $badConfig")
}
```

output without env
```
Env vars: {}
good  Config(connectTimeout=10)
bad Config(connectTimeout=100)
```

output with env `SERVICE_CONNECT_TIMEOUT=3000`
```
Env vars: {CONNECT_TIMEOUT=3000}
good  Config(connectTimeout=3000)
Exception in thread "main" com.sksamuel.hoplite.ConfigException: Error loading config because:

    Config value 'connect_timeout' at (bad.yaml:0:17) was unused
    at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:191)
    at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:188)
    at com.sksamuel.hoplite.fp.ValidatedKt.getOrElse(Validated.kt:114)
    at com.sksamuel.hoplite.ConfigLoader.returnOrThrow(ConfigLoader.kt:188)
    at CheckConfigKt.makeConfig(CheckConfig.kt:48)
    at CheckConfigKt.main(CheckConfig.kt:32)
    at CheckConfigKt.main(CheckConfig.kt)
```

I would like to avoid removing strict() or renaming the config to camelCase.

**Comment by sksamuel** [comment]
2.2.0 has a fix

**Comment by bt-wil** [comment]
Thanks for the fix!  I was testing some cases that I had and encountered error with nesting.

good.yaml
```
serviceName: "good"

timeoutConfig:
  connectSec: 10
  socketSec: 11
```

bad.yaml
```
service_name: "bad"

timeout_config:
  connect_sec: 100
  socket_sec: 101
```

code using v2.2.0
```
import com.sksamuel.hoplite.ConfigLoaderBuilder
import com.sksamuel.hoplite.addFileSource
import com.sksamuel.hoplite.sources.EnvironmentVariablesPropertySource
import java.io.File

data class Config(
    val serviceName: String,
    val timeoutConfig: TimeoutConfig,
)

data class TimeoutConfig(
    val socketSec: Int,
    val connectSec: Int,
)

fun makeConfig(configFile: String, envVars: Map<String, String>): Config {
    val envSource =
        EnvironmentVariablesPropertySource(
            useUnderscoresAsSeparator = true,
            allowUppercaseNames = true,
        ) { envVars }
    return ConfigLoaderBuilder.default()
        .addPropertySource(envSource)
        .addFileSource(File(configFile))
        .strict()
        .build()
        .loadConfigOrThrow()
}

fun main() {
    val prefix = "SERVICE_"
    val envVars =
        System.getenv().filterKeys { it.startsWith(prefix) }.mapKeys { it.key.removePrefix(prefix) }

    println("Env vars: $envVars")

    val goodConfig = makeConfig("good.yaml", envVars)
    println("good $goodConfig")

    val badConfig = makeConfig("bad.yaml", envVars)
    println("bad  $badConfig")
}
```

no override looks fine.
```
Env vars: {}
good Config(serviceName=good, timeoutConfig=TimeoutConfig(socketSec=11, connectSec=10))
bad  Config(serviceName=bad, timeoutConfig=TimeoutConfig(socketSec=101, connectSec=100))
```

top level override looks fine.

```
Env vars: {SERVICE_NAME=override}
good Config(serviceName=override, timeoutConfig=TimeoutConfig(socketSec=11, connectSec=10))
bad  Config(serviceName=override, timeoutConfig=TimeoutConfig(socketSec=101, connectSec=100))
```


top level override and one nested value override throws error.
```
Env vars: {SERVICE_NAME=override, TIMEOUT_CONFIG__CONNECT_SEC=999}
good Config(serviceName=override, timeoutConfig=TimeoutConfig(socketSec=11, connectSec=999))
Exception in thread "main" com.sksamuel.hoplite.ConfigException: Error loading config because:

    - Could not instantiate 'Config' because:

        - 'timeoutConfig': - Could not instantiate 'TimeoutConfig' because:

            - 'socketSec': Missing from config
    at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:191)
    at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:188)
    at com.sksamuel.hoplite.fp.ValidatedKt.getOrElse(Validated.kt:115)
    at com.sksamuel.hoplite.ConfigLoader.returnOrThrow(ConfigLoader.kt:188)
    ...
```

service name override and two (all) values override throws a different error.

```
Env vars: {TIMEOUT_CONFIG__SOCKET_SEC=123, SERVICE_NAME=override, TIMEOUT_CONFIG__CONNECT_SEC=999}
good Config(serviceName=override, timeoutConfig=TimeoutConfig(socketSec=123, connectSec=999))
Exception in thread "main" com.sksamuel.hoplite.ConfigException: Error loading config because:

    Config value 'timeout_config.connect_sec' at (bad.yaml:3:15) was unused

    Config value 'timeout_config.socket_sec' at (bad.yaml:4:14) was unused
    at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:191)
    at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:188)
    at com.sksamuel.hoplite.fp.ValidatedKt.getOrElse(Validated.kt:115)
    at com.sksamuel.hoplite.ConfigLoader.returnOrThrow(ConfigLoader.kt:188)
    ...
```

**Comment by bt-wil** [comment]
I was recently doing an upgrade to `2.7.5`, and this behavior still exists. (https://github.com/sksamuel/hoplite/issues/312#issuecomment-1175405203)

@sksamuel , would this be still considered a bug?


Environment variables are prefixed with `SERVICE_`, ie: 
* `SERVICE_SERVICE_NAME`
* `SERVICE_TIMEOUT_CONFIG__SOCKET_SEC`
* `SERVICE_TIMEOUT_CONFIG__CONNECT_SEC`

Updated code to reflect new changes in the library.

```
import com.sksamuel.hoplite.ConfigLoaderBuilder
import com.sksamuel.hoplite.addFileSource
import com.sksamuel.hoplite.sources.EnvironmentVariablesPropertySource
import java.io.File

data class Config(
    val serviceName: String,
    val timeoutConfig: TimeoutConfig,
)

data class TimeoutConfig(
    val socketSec: Int,
    val connectSec: Int,
)

fun makeConfig(configFile: String, envVars: Map<String, String>): Config {
    val envSource =
        EnvironmentVariablesPropertySource(
            useUnderscoresAsSeparator = true,
            allowUppercaseNames = true,
            environmentVariableMap = { envVars },
        )
    return ConfigLoaderBuilder.default()
        .addPropertySource(envSource)
        .addFileSource(File(configFile))
        .strict()
        .build()
        .loadConfigOrThrow()
}

fun main() {
    val prefix = "SERVICE_"
    val envVars =
        System.getenv().filterKeys { it.startsWith(prefix) }.mapKeys { it.key.removePrefix(prefix) }

    println("Env vars: $envVars")

    val goodConfig = makeConfig("good.yaml", envVars)
    println("good $goodConfig")

    val badConfig = makeConfig("bad.yaml", envVars)
    println("bad  $badConfig")
}
```

Errors remain the same as the previous version.
