### ISSUE TITLE
Unable to decode Double and Float from a whole number "X" or "X.0" (hocon tested)

### ISSUE THREAD

**Issue by Tomasan7** [sksamuel/hoplite#330]
Considering the following `config.conf` (hocon):
```yaml
double: 5.0
float: 5.0
```
And the following code:
```kotlin
fun main()
{
    val config = ConfigLoader().loadConfigOrThrow<Config>("/config.conf")
    print("double: ${config.double}")
    print("float: ${config.float}")
}

data class Config(val double: Double, val float: Float)
```

Putting either `5` or `5.0` as a value for `Double` or `Float` results in the following error:
```
Exception in thread "main" com.sksamuel.hoplite.ConfigException: Error loading config because:

    - Could not instantiate 'Config' because:

        - 'double': Required type Double could not be decoded from a Long value: 5 (classpath:/config.conf:1)

        - 'float': Required type Float could not be decoded from a Long value: 5 (classpath:/config.conf:2)
	at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:192)
	at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:189)
	at com.sksamuel.hoplite.fp.ValidatedKt.getOrElse(Validated.kt:115)
	at com.sksamuel.hoplite.ConfigLoader.returnOrThrow(ConfigLoader.kt:189)
	at MainKt.main(Main.kt:30)
	at MainKt.main(Main.kt)
```
But when you put there for example `0.1` or a different it works as expected.

**Comment by sksamuel** [comment]
Fixed in 2.5.2

Thanks for the bug report.
